Feature/moko-resources
BottleRocketStudios/kmm-demo pull request #13
Opened 2023-11-12 15:57 UTC by VanyaHuamanBottleRocket

Add Moko Resources

2023-11-13 15:31 UTC, br-Emery approved these changes

2023-11-13 19:07 UTC, BottleRocket-Colin requested changes
Let's take a little time and discuss possible changes.

2023-11-13 19:07 UTC, BottleRocket-Colin commented on shared/build.gradle.kts
>                  implementation(libs.ktor.client.darwin)
Do these need to be on all platforms as they are also in common?

2023-11-13 19:07 UTC, BottleRocket-Colin commented on shared/src/commonMain/resources/MR/colors/colors.xml
> +    <color name="primary">
Let's discuss if we need these colors here or if they can just live in common colors.kt file.

2023-11-15 20:33 UTC, BottleRocket-Colin approved these changes

2023-11-15 20:33 UTC, merged